/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package swp.tuilmenau.carduinodroid;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int ic_launcher=0x7f020000;
    }
    public static final class id {
        public static final int button1=0x7f070008;
        public static final int imageView1=0x7f070007;
        public static final int preview=0x7f070009;
        public static final int radio0=0x7f070005;
        public static final int radio1=0x7f070006;
        public static final int radioGroup1=0x7f070004;
        public static final int textView1=0x7f070000;
        public static final int textView2=0x7f070001;
        public static final int textView3=0x7f070002;
        public static final int textView4=0x7f070003;
    }
    public static final class layout {
        public static final int main=0x7f030000;
    }
    public static final class raw {
        public static final int carduinodroid=0x7f050000;
        public static final int horn=0x7f050001;
    }
    public static final class string {
        public static final int CloseButton=0x7f060003;
        public static final int IP_title=0x7f060002;
        public static final int LOG_All=0x7f060004;
        public static final int LOG_Level_title=0x7f060007;
        public static final int LOG_WarningsOnly=0x7f060006;
        public static final int LocalIP=0x7f060001;
        public static final int LogoDesc=0x7f060008;
        public static final int app_name=0x7f060000;
        public static final int empty=0x7f060005;
    }
    public static final class xml {
        public static final int accessory_filter=0x7f040000;
        public static final int device_filter=0x7f040001;
    }
}
